### ISSUE TITLE
Recent version doesn't let me make duplicate cards.

### ISSUE THREAD

**Issue by Etyre** [taylormitchell/ankify_roam#54]
A recent version of Ankify roam, the special one that I downloaded to fix my [cloze deletion problem](https://github.com/taylormitchell/ankify_roam/issues/38), broke my workflow.

![](https://imgs.xkcd.com/comics/workflow_2x.png)

Specifically, this version doesn't let me make (or update?) duplicate cards. This is a totally reasonable feature, but I've intentionally made a few duplicates of my cards for the powers of two.

I guess that this is known to be bad Anki practice, but maybe you want to leave an option to make duplicate cards. Very low priority for me.

Here are the error logs:

```
(base) atlasfellowship@Claires-MBP-4 fucking_around % ankify_roam add --deck="Daily review::Incremental Reading" Roam_Backup/json/eli.json 
2022-08-23 21:51:22,817 - INFO - Setting up Ankifier
2022-08-23 21:51:22,992 - INFO - Loading Roam Graph
2022-08-23 21:51:39,238 - INFO - Found 1018 blocks with ankify tag
2022-08-23 21:52:10,012 - ERROR - Failed ankifying <Block(uid='_u0wtNjFg', string='{{[[embed]...')> during upload to anki
Traceback (most recent call last):
  File "/Users/atlasfellowship/opt/anaconda3/lib/python3.9/site-packages/ankify_roam/ankifiers.py", line 103, in ankify
    anki.add_note(ankified_note)
  File "/Users/atlasfellowship/opt/anaconda3/lib/python3.9/site-packages/ankify_roam/anki.py", line 54, in add_note
    return _invoke("addNote", note=anki_dict)
  File "/Users/atlasfellowship/opt/anaconda3/lib/python3.9/site-packages/ankify_roam/anki.py", line 35, in _invoke
    raise DuplicateError(response['error'])
ankify_roam.anki.DuplicateError: cannot create note because it is a duplicate
2022-08-23 21:52:12,313 - ERROR - Failed ankifying <Block(uid='DtyiCZrt8', string='All expone...')> during upload to anki
Traceback (most recent call last):
  File "/Users/atlasfellowship/opt/anaconda3/lib/python3.9/site-packages/ankify_roam/ankifiers.py", line 103, in ankify
    anki.add_note(ankified_note)
  File "/Users/atlasfellowship/opt/anaconda3/lib/python3.9/site-packages/ankify_roam/anki.py", line 54, in add_note
    return _invoke("addNote", note=anki_dict)
  File "/Users/atlasfellowship/opt/anaconda3/lib/python3.9/site-packages/ankify_roam/anki.py", line 35, in _invoke
    raise DuplicateError(response['error'])
ankify_roam.anki.DuplicateError: cannot create note because it is a duplicate
2022-08-23 21:52:14,214 - ERROR - Failed ankifying <Block(uid='bJ8Ge5YO-', string='2^2 = #ank...')> during upload to anki
Traceback (most recent call last):
  File "/Users/atlasfellowship/opt/anaconda3/lib/python3.9/site-packages/ankify_roam/ankifiers.py", line 103, in ankify
    anki.add_note(ankified_note)
  File "/Users/atlasfellowship/opt/anaconda3/lib/python3.9/site-packages/ankify_roam/anki.py", line 54, in add_note
    return _invoke("addNote", note=anki_dict)
  File "/Users/atlasfellowship/opt/anaconda3/lib/python3.9/site-packages/ankify_roam/anki.py", line 35, in _invoke
    raise DuplicateError(response['error'])
ankify_roam.anki.DuplicateError: cannot create note because it is a duplicate
2022-08-23 21:52:14,314 - ERROR - Failed ankifying <Block(uid='X-AnXDbJy', string='2^3 = #ank...')> during upload to anki
Traceback (most recent call last):
  File "/Users/atlasfellowship/opt/anaconda3/lib/python3.9/site-packages/ankify_roam/ankifiers.py", line 103, in ankify
    anki.add_note(ankified_note)
  File "/Users/atlasfellowship/opt/anaconda3/lib/python3.9/site-packages/ankify_roam/anki.py", line 54, in add_note
    return _invoke("addNote", note=anki_dict)
  File "/Users/atlasfellowship/opt/anaconda3/lib/python3.9/site-packages/ankify_roam/anki.py", line 35, in _invoke
    raise DuplicateError(response['error'])
ankify_roam.anki.DuplicateError: cannot create note because it is a duplicate
2022-08-23 21:52:14,416 - ERROR - Failed ankifying <Block(uid='w-EG2gIzI', string='2^4 = #ank...')> during upload to anki
Traceback (most recent call last):
  File "/Users/atlasfellowship/opt/anaconda3/lib/python3.9/site-packages/ankify_roam/ankifiers.py", line 103, in ankify
    anki.add_note(ankified_note)
  File "/Users/atlasfellowship/opt/anaconda3/lib/python3.9/site-packages/ankify_roam/anki.py", line 54, in add_note
    return _invoke("addNote", note=anki_dict)
  File "/Users/atlasfellowship/opt/anaconda3/lib/python3.9/site-packages/ankify_roam/anki.py", line 35, in _invoke
    raise DuplicateError(response['error'])
ankify_roam.anki.DuplicateError: cannot create note because it is a duplicate
2022-08-23 21:52:14,513 - ERROR - Failed ankifying <Block(uid='D86wmsR_H', string='2^5 = #ank...')> during upload to anki
Traceback (most recent call last):
  File "/Users/atlasfellowship/opt/anaconda3/lib/python3.9/site-packages/ankify_roam/ankifiers.py", line 103, in ankify
    anki.add_note(ankified_note)
  File "/Users/atlasfellowship/opt/anaconda3/lib/python3.9/site-packages/ankify_roam/anki.py", line 54, in add_note
    return _invoke("addNote", note=anki_dict)
  File "/Users/atlasfellowship/opt/anaconda3/lib/python3.9/site-packages/ankify_roam/anki.py", line 35, in _invoke
    raise DuplicateError(response['error'])
ankify_roam.anki.DuplicateError: cannot create note because it is a duplicate
2022-08-23 21:52:14,613 - ERROR - Failed ankifying <Block(uid='FH7Ftrvq6', string='2^6 = #ank...')> during upload to anki
Traceback (most recent call last):
  File "/Users/atlasfellowship/opt/anaconda3/lib/python3.9/site-packages/ankify_roam/ankifiers.py", line 103, in ankify
    anki.add_note(ankified_note)
  File "/Users/atlasfellowship/opt/anaconda3/lib/python3.9/site-packages/ankify_roam/anki.py", line 54, in add_note
    return _invoke("addNote", note=anki_dict)
  File "/Users/atlasfellowship/opt/anaconda3/lib/python3.9/site-packages/ankify_roam/anki.py", line 35, in _invoke
    raise DuplicateError(response['error'])
ankify_roam.anki.DuplicateError: cannot create note because it is a duplicate
2022-08-23 21:52:33,590 - INFO - Results: 79 notes added, 3 updated, 929 unchanged, 7 failed
```

**Comment by Etyre** [comment]
Oh. Actually it looks like the old version that I was running also had this "bug", but I hadn't noticed it amongst the 70-odd cloze errors.

**Comment by taylormitchell** [comment]
Yeah I'm pretty sure this has always been the case, and it's enforced Anki's side. I'll see if there's an option to disable it though. Seems fine to me to allow users to create duplicates.
