### ISSUE TITLE
I can't seem to import cards with cloze deletions?

### ISSUE THREAD

**Issue by Etyre** [taylormitchell/ankify_roam#8]
Hey. I'm trying out ankify_roam. 

Thanks for making this! Looking through the README, it looks like you already thought of and implemented all the features I was looking for.

However, when trying to import new anki cards from roam for the first time, it looks like on the "basic" style cards were imported. The "cloze" style cards didn't work.

I get the following error message: 

`MacBook-Pro-2:ankify_roam elityre$ ankify_roam add eli.json
2020-10-04 01:45:28,910 - INFO - Setting up Ankifier
2020-10-04 01:45:29,091 - INFO - Loading Roam Graph
2020-10-04 01:45:35,164 - INFO - Fetching blocks to ankify
2020-10-04 01:45:35,258 - INFO - Ankifying 4 blocks
2020-10-04 01:45:35,392 - ERROR - Failed ankifying <Block(uid='EZfmNWARo', string='This is al...')> during upload to anki
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/ankify_roam/ankifiers.py", line 83, in ankify
    anki.add_note(anki_note)
  File "/usr/local/lib/python3.7/site-packages/ankify_roam/anki.py", line 52, in add_note
    return _invoke("addNote", note=anki_dict)
  File "/usr/local/lib/python3.7/site-packages/ankify_roam/anki.py", line 37, in _invoke
    raise GenericResponseError(response['error'])
ankify_roam.anki.GenericResponseError: The field values you have provided would make an empty question on all cards.
2020-10-04 01:45:35,440 - ERROR - Failed ankifying <Block(uid='8ScQi1ftQ', string='This is a ...')> during upload to anki
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/ankify_roam/ankifiers.py", line 83, in ankify
    anki.add_note(anki_note)
  File "/usr/local/lib/python3.7/site-packages/ankify_roam/anki.py", line 52, in add_note
    return _invoke("addNote", note=anki_dict)
  File "/usr/local/lib/python3.7/site-packages/ankify_roam/anki.py", line 37, in _invoke
    raise GenericResponseError(response['error'])
ankify_roam.anki.GenericResponseError: The field values you have provided would make an empty question on all cards.
2020-10-04 01:45:35,490 - ERROR - Failed ankifying <Block(uid='cBUVxdLUr', string='This {{c1:...')> during upload to anki
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/ankify_roam/ankifiers.py", line 83, in ankify
    anki.add_note(anki_note)
  File "/usr/local/lib/python3.7/site-packages/ankify_roam/anki.py", line 52, in add_note
    return _invoke("addNote", note=anki_dict)
  File "/usr/local/lib/python3.7/site-packages/ankify_roam/anki.py", line 37, in _invoke
    raise GenericResponseError(response['error'])
ankify_roam.anki.GenericResponseError: The field values you have provided would make an empty question on all cards.
2020-10-04 01:45:35,491 - INFO - Added 1 new notes and updated 0 existing notes`

It seems like it doesn't like that 4 of the blocks tagged "#ankify" don't have children (nor does it like it if they have empty children). From which I infer that the program is treating those blocks as basic cards instead of cloze deletion cards?

What should I do about this?

**Comment by Etyre** [comment]
Apparently, I _can_ import cards that don't have children as long as they don't have curly brackets.

**Comment by taylormitchell** [comment]
Hey Etyre,

Hmm that is strange. Looks like ankify_roam is trying to create some cloze cards but it didn't convert the cloze deletions to the right anki syntax (so anki doesn't see any cloze deletions, which it doesn't like).

I'm guessing it's some issue with the cloze syntax or how ankify_roam is handling it. Could you share the blocks (including children) which are having this issue? Just copy pasting them here is fine.

**Comment by Etyre** [comment]
Yep.

The following is the text of the blocks that I tried to import.

- This is a test but the answer is hungry #ankify
    - hungry
- This is also a test. There should be a cloze on the last {word}. #ankify
    - Test
- This is a {third} test. There are {three} clozes {here}. #ankify
- This {c1|last} test should have {c1|two} clozes at once and {c2|this one} separately. #ankify
- trying one last {time} #ankify 
- This is a basic card #ankify
- Testing to see which deck this card goes into #ankify
    - I'm betting it makes a new "Default" deck.

It seems like as long as the block doesn't have a curly bracket, it gets added as a card to anki.

**Comment by taylormitchell** [comment]
Yeah, it's got something to do with how ankify_roam is handling cloze cards. I can't replicate the error on my end though. Can you send me some info about your setup?

- Did you install ankify_roam using `pip install ankify_roam` or `pip install git+https://github.com/taylormitchell/ankify_roam.git`? If the later, can you check the version by running `ankify_roam --version`?
- Python version? `python --version`
- Anki version? Open Anki > Anki > About > Version ?

I would also just try installing the latest version of ankify_roam via git. I've made some bug fixes recently, none were for the issue you're experiencing... but who knows, maybe they're related.

**Comment by Etyre** [comment]
Let's see.


- I don't remember how I installed ankify_roam. I think I was missing some dependency so that I tried both, and then figured out the problem. 
  - ankify_roam version = ankify_roam 0.0.7
- Python version = Python 3.7.7
- Anki version = 2.1.13

**Comment by Etyre** [comment]
Alright. I deleted all the "ankify_roam" files and downloaded with the git link. (However, this did not produce a new directory in the location where I ran the command, as I was expecting. Is that normal?) 

I tried it again, I ran into the same problem again.

**Comment by Etyre** [comment]
I updated to the latest version of anki, and that seemed to fix the problem.

**Comment by taylormitchell** [comment]
Nice! Glad to hear it.

I'll try downgrading my version of anki to track down the problem so I can either fix it or put a particular anki version in the ankify_roam prerequisites.
